// Env is augmented from worker-configuration.d.ts (generated by `wrangler types`)
// plus the secrets we provision via `wrangler secret put`.
declare global {
  interface Env {
    DEEPGRAM_API_KEY: string;
  }
}

export default {
  async fetch(_req: Request, _env: Env): Promise<Response> {
    return new Response("ok");
  },
} satisfies ExportedHandler<Env>;
